---
project:
  type: website

format:
  html:
    callout-appearance: simple
    theme: darkly
  revealjs:
    footer: "{{< meta title >}}: <https://razekmh.github.io/talks>"
    hash-type: number
    history: false
    incremental: true
    link-external-icon: true
    link-external-newwindow: true
    mermaid:
      theme: dark
    slide-number: true
    theme: dark
    transition: fade

website:
  # google-analytics: G-XXXXXXXXXX
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://razekmh.dev
        target: _blank
      - icon: github
        href: https://razekmh.dev/talks
        target: _blank
  title: ""
