---
name: Quarto Publish

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: razekmh/.github/actions/github-pages/quarto@f9a730975922aae748356e721d27623cb4a0f480 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          requirements-txt: ${{ github.workspace }}/requirements.txt
